// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqM1OrFAuSoHuix6lepvOfV2axE8PWIJQ',
    appId: '1:811006119352:web:eaf303bf56ec4fc8b7934d',
    messagingSenderId: '811006119352',
    projectId: 'invenerp',
    authDomain: 'invenerp.firebaseapp.com',
    storageBucket: 'invenerp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3YOKhjezcHkUZILbTcply0b68Evtxvg',
    appId: '1:811006119352:android:950c303c0ddb475eb7934d',
    messagingSenderId: '811006119352',
    projectId: 'invenerp',
    storageBucket: 'invenerp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK4TxfAHcUsMZsnKxIrMDUDHFAZSsVIdg',
    appId: '1:811006119352:ios:55fbff0aba5e5009b7934d',
    messagingSenderId: '811006119352',
    projectId: 'invenerp',
    storageBucket: 'invenerp.firebasestorage.app',
    iosBundleId: 'com.example.invenErp',
  );
}
